- alias: 'Start HomeKit'
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - service: homekit.start
- id: 2ce80d78611c4fd6909580653114d2bc
  alias: test at 3:30am
  trigger:
  - at: '3:30:00'
    platform: time
  action:
  - service: zwave.test_network
  hide_entity: true

- id: 383e1a78e3784aae8d7864d4de3a01c0
  alias: heal at 4:30am
  trigger:
  - at: '4:30:00'
    platform: time
  action:
  - service: zwave.heal_network
  hide_entity: true

- id: '1544279276807'
  alias: Return all dimmers to full brightness in morning
  trigger:
    platform: time
    at: 04:50:00
  condition: []
  action:
  - service: script.set_main_floor_dimmers_to_full_brightness_then_off
