- alias: test at 6:30am
  hide_entity: true
  trigger:
    platform: time
    at: '6:30:00'
  action:
    service: zwave.test_network
  id: 2ce80d78611c4fd6909580653114d2bc
- alias: heal at 7:30am
  hide_entity: true
  trigger:
    platform: time
    at: '7:30:00'
  action:
    service: zwave.heal_network
  id: 383e1a78e3784aae8d7864d4de3a01c0

- id: '1544279276807'
  alias: Return all dimmers to full brightness
  trigger:
    platform: time
    at: '10:00:00'
  condition: []
  action:
  - alias: ''
    service: script.set_dimmers_to_full_brightness
